language: ruby
rvm:
- 2.7
before_install:
- gem update --system
- gem install bundler
- gem install aws-sdk-lambda
- gem install aws-sdk-cloudwatchevents
install:
- rake run_bundler
script:
- rake test
deploy:
- provider: lambda
  function_name: SierraHoldingParser-dev
  description: A function that parses holding records from the Sierra API
  region: us-east-1
  role: arn:aws:iam::224280085904:role/lambda_basic_execution
  runtime: ruby2.7
  timeout: 60
  module_name: app
  handler_name: handle_event
  event:
    event_source_arn: arn:aws:kinesis:us-east-1:224280085904:stream/SierraHoldingsParser-dev
    batch_size: 10
    maximum_record_age_in_seconds: 86400
    bisect_batch_on_function_error: true
    maximum_retry_attempts: 3
    starting_position: LATEST
  environment:
    variables:
     LOG_LEVEL: debug
     PLATFORM_API_BASE_URL: https://dev-platform.nypl.org/api/v0.1/
     IN_SCHEMA_TYPE: SierraHolding
     OUT_SCHEMA_TYPE: Holding
     KINESIS_STREAM: HoldingPostRequest-dev
     LOCATIONS_JSONLD_URL: https://s3.amazonaws.com/nypl-core-objects-mapping-production/by_sierra_location.json
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  on:
    branch: development
- provider: lambda
  function_name: SierraHoldingParser-qa
  description: A function that parses holding records from the Sierra API
  region: us-east-1
  role: arn:aws:iam::946183545209:role/lambda-full-access
  runtime: ruby2.7
  timeout: 60
  module_name: app
  handler_name: handle_event
  event:
    event_source_arn: arn:aws:kinesis:us-east-1:946183545209:stream/SierraHoldingParser-qa
    batch_size: 10
    maximum_record_age_in_seconds: 86400
    bisect_batch_on_function_error: true
    maximum_retry_attempts: 3
    starting_position: LATEST
  environment:
    variables:
      LOG_LEVEL: debug
      PLATFORM_API_BASE_URL: https://qa-platform.nypl.org/api/v0.1/
      IN_SCHEMA_TYPE: SierraHolding
      OUT_SCHEMA_TYPE: Holding
      KINESIS_STREAM: HoldingPostRequest-qa
      LOCATIONS_JSONLD_URL: https://s3.amazonaws.com/nypl-core-objects-mapping-production/by_sierra_location.json
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  on:
    branch: qa
- provider: lambda
  function_name: SierraHoldingParser-production
  description: A function that parses holding records from the Sierra API
  region: us-east-1
  role: arn:aws:iam::946183545209:role/lambda-full-access
  runtime: ruby2.7
  timeout: 60
  module_name: app
  handler_name: handle_event
  event:
    event_source_arn: arn:aws:kinesis:us-east-1:946183545209:stream/SierraHoldingParser-production
    batch_size: 10
    maximum_record_age_in_seconds: 86400
    bisect_batch_on_function_error: true
    maximum_retry_attempts: 3
    starting_position: LATEST
  vpc:
    subnet_ids:
    - subnet-59bcdd03
    - subnet-5deecd15
    security_group_ids:
    - sg-116eeb60
  environment:
    variables:
      LOG_LEVEL: debug
      PLATFORM_API_BASE_URL: https://platform.nypl.org/api/v0.1/
      IN_SCHEMA_TYPE: SierraHolding
      OUT_SCHEMA_TYPE: Holding
      KINESIS_STREAM: HoldingPostRequest-production
      LOCATIONS_JSONLD_URL: https://s3.amazonaws.com/nypl-core-objects-mapping-production/by_sierra_location.json
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  on:
    branch: main
after_deploy:
- rake set_config
notifications:
  email:
    on_failure: always
env:
  global:
  - secure: iOmVxMj0m8fWU5czQ68kIt+TYeekdvvnt/Q06fVCrTjiyAICuU1I8B5xGvHPn0B0gRJUEmC2Eq460AMw/aEbCg9uHdTEofFmwtpRTkDh0sCQ/ezh5Y/FyQw094cThCcWGOVpudyEfCefJ80Z07MIzDZYJvAD6AqSdQQic/XNXqHYwCqkupt934EyFzxN0DdjeL2ZIJuzU0zPRmXEH3xz2kGXqPYRkDDXUHa6ZwsUfUO3WObcb/VO58e0Vct/l4t/7+5v31d6pGGQxPRuKRV0v5E/yAKihze3jBSh9mLtu4+r8En1mwdMKwD5fZ+KdFYfwuOVBFRY4Dtj247nf6flpi6D7OLO05XFL9Hj/NiN9TdRZrQ0qpxKYqCAXFITiofdQCqLFq/iZokBM97n4BCz8EIs5wof4f7VBpD3+yyOGlkptVtAUOnMuJgoLY9vMQhO85HJ3JgT057ivnuTJQdUIs15O5ZgbkQB99VbfvZwTlIc8Temtw9PVGDTDlRpuLWZ5vinMK6ehCH2zwRI1uKRjLjZvqYc7GHSA2e5POEwUjO64ll8e8nVE/SiuPA/BzPbCea0N0VlXvdVK4jJn474J5ezxgjQqOaHfXKiNUU7apyGvwC+IHIHv2xpbf1ScNY9InWr36hAxIIibkNvc7kJ+FJp1e4J+dpFGKaWpVtva8o=
  - secure: BO7ldpERveqZPr7ndixSeVBEd8NqNSqxlBktPHdQlXYKInfwhPb/7a1GrhteKoLuEa/WC8uWF4H+pHstgLaoUHWZzguae4D5xwI8PBY2PZT857ZGc4cnaL1wfhslEOm8Zs7WBmdXfu/xvLMFWaTc5iZ/TW326lzytT9OgvUzNAM2VMfkIvkYK+u1a8huXLUNsM4aWQX2dIjKYLEUjznxutr49oGzPmiRvsjPiAaP5+wUqL6+AxctcQxUcHL842b3W+Vau9XPXaJ/27Qhod9JARty0T0GGyxEaTQ7rkSCb8ziIAPTPBrxbn3ydKqKPBxHL9+xY810UNkHToabKVu9LMqSsYO42WtpUl+9Ao1uYnSBuZEWQKTgRZebl+UlsBoq6QuHxqXVM88AFIp1S11JdmO6SdCyBdxTjd20YKvUODg2+DvPiEIkEc6CYXKNZWxThnZ5l0BA1QDmuBhx1V3Ll81c1TJewZhNbAAAYy3WpaXP/PhxU0DBpE/ZfiE0T3DvMU8nXPu7ROf2cLvdr6Hbop0Q6jbZpjwPJhHtFfaPQyrq5p4mEobBP0zxKtBoW8BytVqt+UyGfYAmdFXHoB2kOKY6aIO9uIuODN0Ng8j/bbAfvG4JEzH1ZiTtLFaZDjvfxOBI51zwFTJr89DUqoUOtvXvk/9IKg/5e73lkDmakBI=
  - secure: AbUHeL8p6NhXDOX9tuM+jv7PPRaWsdKuV4o158CLjJBTM3vPwiBMieE4BnenqADfVGAQ/IO/flLCTmUJhB7BVdgGqLB7qDWYaLsOgDeYzfthdTo5lvWSv7WN8MoUhI2l0dBtNZUqhcLgQW+ObjLE98LFDwfTEye58c2B81uDxBMBGWO9Sm7gsWwSy+XZJV59Rf64l7vvHrP9WIrfRMxMEPdrW83xvY9UHeu7MQ9hYmiOLa1dXtlJwhoW5EDugOvzoX0A0TsOoIePQzf1cHtgSdYIbm1GGY/8zvtm+uShxQfysR6hNSDcgBVvXgqK8EyPMlsbmIHb+Z184WUQF74Z6s0UoqnfiBSiEd/WvlvLogTKVEMFZtpPA7g5EhrapSQ096giSaOlKTm9DUDMjZQggnxbBFoXGXbtl7z9F4NRQ3ioCvxEvTnLkTVu2SRwNDEHWC1aCDNXSpVAe3QcGO7UluCZsnuXIp7lBIvSm8z+BVTr17Gj5VHtrEw4C3aEczR0Fxc5u9xvCZ9/QhDyv9FK6hkWql2JfCelsRuaSjEL06zNURU/uzGGyz3cnsxLDBvrpgT/NHCkhtLWkuZxpuZj7+4WUcXcHaucJDQdi1LsmuM34fkG7IXBk1hLXKFOJy8IPsXV7LHXi2+kJotgd+Pp4080Vrtxw5ddnPOpMax8xcs=
