language: ruby
rvm:
- 2.7
before_install:
- gem update --system
- gem install bundler
- gem install aws-sdk-lambda
- gem install aws-sdk-cloudwatchevents
install:
- rake run_bundler
script:
- rake test
deploy:
- provider: lambda
  function_name: SierraHoldingParser-dev
  description: A function that parses holding records from the Sierra API
  region: us-east-1
  role: arn:aws:iam::224280085904:role/lambda_basic_execution
  runtime: ruby2.7
  timeout: 60
  module_name: app
  handler_name: handle_event
  environment_variables:
      - "LOG_LEVEL=debug"
      - "PLATFORM_API_BASE_URL=https://dev-platform.nypl.org/api/v0.1"
      - "SCHEMA_TYPE=Holding"
      - "KINESIS_STREAM=HoldingPostRequest-dev"
      - "LOCATIONS_JSONLD_URL=https://s3.amazonaws.com/nypl-core-objects-mapping-production/by_sierra_location.json"
  access_key_id: "$AWS_ACCESS_KEY_ID_DEV"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEV"
  on:
    branch: development
- provider: lambda
  function_name: SierraHoldingParser-qa
  description: A function that parses holding records from the Sierra API
  region: us-east-1
  role: arn:aws:iam::946183545209:role/lambda-full-access
  runtime: ruby2.7
  timeout: 60
  module_name: app
  handler_name: handle_event
  environment_variables:
    - LOG_LEVEL=debug
    - PLATFORM_API_BASE_URL=https://qa-platform.nypl.org/api/v0.1
    - SCHEMA_TYPE=Holding
    - KINESIS_STREAM=HoldingPostRequest-qa
    - LOCATIONS_JSONLD_URL=https://s3.amazonaws.com/nypl-core-objects-mapping-production/by_sierra_location.json
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  on:
    branch: qa
- provider: lambda
  function_name: SierraHoldingParser-production
  description: A function that parses holding records from the Sierra API
  region: us-east-1
  role: arn:aws:iam::946183545209:role/lambda-full-access
  runtime: ruby2.7
  timeout: 60
  module_name: app
  handler_name: handle_event
  event: arn:aws:kinesis:us-east-1:946183545209:stream/SierraHoldingParser-production
  vpc:
    subnet_ids:
    - subnet-59bcdd03
    - subnet-5deecd15
    security_group_ids:
    - sg-116eeb60
  environment_variables:
  - LOG_LEVEL=debug
  - PLATFORM_API_BASE_URL=https://platform.nypl.org/api/v0.1
  - SCHEMA_TYPE=Holding
  - KINESIS_STREAM=HoldingPostRequest-production
  - LOCATIONS_JSONLD_URL=https://s3.amazonaws.com/nypl-core-objects-mapping-production/by_sierra_location.json
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  on:
    branch: production
after_deploy:
- rake set_config
notifications:
  email:
    on_failure: always
env:
  global:
  - secure: HTGJVc7TlaeeddbC0LEYREPSzkUz2Vss9t6lRJ8yMbaJFXWmoTECeMrXhdjr8Pe0WcxEMiTLbdbMLVZkMIHjqFpj7y4qXmirSPeAyCdLqr/cJPj2djNPkeX2uLZecchAie2D9bQOoh2i7Cytj5txsVrVJ7QrlG/6yu06Ntf8JRE92W3BWUBsBYPEuNWxVOddKPm/PStHjYOvkH8HwS64EnKCOBZCwHtk4rp/QdGvrZwSvdJxTiAVaQqcTJQ9FgT/+RCKyP0xeS0F8jQlbFnX9wUULjnvzR4+PehKtvRuDvu1/NrxgiNGzH6/TBuQqh/OirvwOmz/h5uDH9f79hjVXs16Virnw7u+bgu63c2OaEfGCjHwySULTdTo7G3XSgccTNdVJRutbOMxkQpQvlkkvs4dy2UzJ20mHPe2URCRQnPGqZQC+otCYp/SfkcH474/hMV8Wxb0bd+AE1jUI8PR3y8lFjwekJ0eAhGOj+3pFWjKjwV5ZTTki532ti0LZ94nAkCr5mb4RvdL0mUwj1HNJw8bmgi2MxFOB2pGHN5g+Ej2pJhzB0d+98ddCjvg0UuzRq3VRjHO4NLTlePw9VPDkRPF7HXeaglL2eQLOrZvygEhbz+q5NBUeXe3Kj/mOu2/jn09TXxoPOCl4mC32A1oxB7fx0J2RhyxeMPMcGPO7oQ=
  - secure: Injke4qxOwSn5W51V9INBES0wZvVKIBcB6RHw9sbV0X/ye7D0T+5s+t4TgHeXI3SZ4q8HLsZpkKywG7GXKMA3YDOeIDb2fEzQS0M+hO66xawrmrlU8l0G1wc5NrjE1+tfUcrNMJqVaXOjQ5XteHq5ub9ff4Sv/UEAlLSP52bSyGLelOboZcyAt21ARJyB2QldUzhhSRNaNY+VW6hUVYsENiQdflit2ZY5LN9/Gj5uhJDDE8DgHoJWy/26jW3wqm2UIztNvY/WNijnF0LBZT5zzHQjBZ/UC1cwDWrGUUETYpnlV0iHpFHZxfCV3SAPqV13KtE//Vt+b0fTXiabyzdceNx1hvRA56ytmck+TRdCJ0yJ5RuL1xBx+1PTYdXJGcluSPBoIB2+ZjbIC/xPXdyM8y9KUMkpBCNeOz5+7wBcFUbubRtMWB6tRtsjW9mS22zjM+NtDD7/91Avo9aNz4LD6fNExR2xYCiwcG/RGGSBCF/y78h9EtA8GFLSwN/qoz6ETqQG952YuEEMQa2UzSujhnwrpN/a1uDULvjLSIdqNThiavSSfFMEFWISjMwu5HcW/EvU33+Cc1NqIEvN2tWsWQrO/RUpn0u9xISaNL2gvVL1YU6Cuw0p5Ki3a9hp2pov6hq9YispcApanuYffCKdyn7AhFYgs5NypRn2wO1yRo=
  - secure: ICaGpUfAqUPm4d31BL1iAtKLpk6LNpIzAMK4ees2003I34qTjZ7x7lQdVCSJFywjQgnmqENMG63O1HVmoZFG+eQkX1RYHna0pvFJ+96UAAOWYu69IoCYGMFHb1viBTCurj1Zl5UbiIkSbDjLTLVe8qmFCmFIFI7kbkgarNxdLH3KuAVfxp6N1CLCJcqMiqGm9AG1x+izAWiWLu2awYB/2PzV1niilQuhz/7jfXf64pF9pvHTYnkumYrzQjQg3qDFqWL0L2Fa6RlwyexucElTaAyokUgnGKyoVrJEpMwYcVsPYAjNvK/+TH8mAWfK6XZnV1XmsdWF5CiZMByphhkhq02Fy9/bHha3xcEtw2xmZwwu/lgTt4Y1gv5DQPAfmviyY+ZuBhpSczFjnml7ccrPZ6KqeNEdBOFeTn8ASHwGvDVWPbhTtYgn3HEW03bA1zyoIT46qBBjCOTgDq/XWcCLnJVSk+5oaJlJItTgmzWXSwDPyfAlL6g6FBUb8RlcSpsuCl6d5ZsaND+XcoYCjbTdUPzpE8GRQT+XprhN0Ua6vyWJecZYiz1E78/J+3sn6BrL+EBptxJ7F0Fn2z3VSuhxqzWeODIy1S1Oc2gzpJz2zu6pvNYZxhq5LEfyuItyCCGi0QWcQm+5XKdv9jfU/M8YUcDNuvMEHarr5H5Mzs9qzDw=
