name: Test and deploy
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
      - name: Install dependencies
        run: ./provisioning/package.sh
      - name: Run test suite
        run: |
          bundle exec rspec
  deploy-qa:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/qa'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::946183545209:role/GithubActionsDeployerRole
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
      - name: Package app
        run: bash provisioning/package.sh
      - uses: hashicorp/setup-terraform@v2
      - name: Deploy app to QA
        run: |
          terraform -chdir=provisioning init -input=false
          terraform -chdir=provisioning workspace select qa
          terraform -chdir=provisioning apply -auto-approve -input=false
  deploy-production:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/production'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::946183545209:role/GithubActionsDeployerRole
          aws-region: us-east-1
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
      - name: Package app
        run: bash provisioning/package.sh
      - uses: hashicorp/setup-terraform@v2
      - name: Deploy app to production
        run: |
          terraform -chdir=provisioning init -input=false
          terraform -chdir=provisioning workspace select production
          terraform -chdir=provisioning apply -auto-approve -input=false

